#!/bin/sh

VOL="$(pulsemixer --get-volume | awk '{print $1}')"

if [ "$(pulsemixer --get-mute)" = 1 ]; then
    printf "\x0d󰝟 Muted\x0b " 
elif [ "$VOL" -ge "70" ]; then
    printf "\x0d󰕾 %s%%\x0b " "$VOL"
elif [ "$VOL" -ge "30" ]; then
    printf "\x0d󰖀 %s%%\x0b " "$VOL"
elif [ "$VOL" -ge "1" ]; then
    printf "\x0d󰕿 %s%%\x0b " "$VOL"
else
    printf "\x0d󰖁 %s%%\x0b " "$VOL"
fi
