#!/bin/sh

# Get the list of active network connections
if nmcli -t -f TYPE,STATE c show --active | grep -q ":activated" | head -n 1; then
    # Ping test to check internet connectivity
    if ping -q -c 1 -W 1 google.com > /dev/null; then
        # Get the name and type of the active connection
        CON_NAME=$(nmcli -t -f NAME c show --active | head -n 1)
        CON_TYPE=$(nmcli -t -f TYPE c show --active | head -n 1)

        # Check if the connection is wireless
        if [[ "$CON_TYPE" =~ (wifi|wireless) ]]; then
            printf "\x0e󰖩 %s\x0b\n" "$CON_NAME"
        else
            printf "\x0e󰖟 Connected\x0b\n"
        fi
    else
        printf "\x0e󰖪 Disconnected\x0b\n"
    fi
else
    # No active network connection 
    printf "\x0e󰖪 Disconnected\x0b\n"
fi
